import "./components/header"
import "./components/index"
import "./components/sliders"
import "./components/lazyImg"
import "./components/modals"
import "./components/two-side-to-grid"
import "./components/miniForm"
import "./components/mailingBanner"
import "./components/about-company"
import "./components/our-partners"
import "./components/stories"
import "./components/accordeon-block"
// import "./components/locomotive-scroll"
import "./components/service-slider"
import "./components/inside-view"
import "./components/block-accordeon"
import "./components/inside-video"
import "./components/footer"

import "./components/newrubkoff/nbl-header"
import "./components/newrubkoff/nbl-footer"
import "./components/newrubkoff/nbl-burger"
import "./components/newrubkoff/nbl-cardSlider"
import "./components/newrubkoff/nbl-truncate"
import "./components/newrubkoff/nbl-timer"
import "./components/newrubkoff/nbl-map"
import "./components/newrubkoff/nbl-cookies"

